module.exports = {
    "article":"article",
    "header":"header",
    "articles":"articles",
    'InnerBanner': 'banner',
    'TC_Center_WhiteBG': 'common-heading',
    'TC_Center_WhiteBG90': 'common-heading',
    'TC_Center_WhiteBG100': 'common-heading',
    'TCM_ImageRight': 'TCM_image-right',
    'TCM_ImageLeft': 'TCM_image-left',
    'TCWithTCL_TealBG_6Box': 'title-content-3col',
    'TCMWithTCL_ImageCenter': 'tcmc',
    'TCM_BgImageRight': 'fifty-fity-image-right',
    'TCM_BgImageRightBGWhite': 'fifty-fity-image-right',
    'TCWithTCML_3icon_Top': 'threeicon-top',
    'TWithTCL_WhiteBG_6Sec': 'roundicon-3col-bgwhite',
    'TWithTCL_GrayBG_6Sec': 'roundicon-3col-bgwhite',
    'CTA_Last': 'cta-last',
    'CTA_Bg_Center': 'cta-bg',
    'TCMWithTCL_BGImage_8Box': 'bgimage-eightbox',
    'TCMWithTCL_LightBGImage_8Box': 'lightbgTextblack',
    'TCMWithTCL_LeftImage': 'leftimage-tcml',
    'CTA_DrakBG': 'cta-blue',
    'CTA_ImageBG': 'cta-blue',
    'TCWithTCL_Teal_4Box': 'card',
    'Development_Process_9icons': 'development-process',
    'TechnologyExpertise_Tab': 'technologytab',
    'TechnologyExpertise_Tab_WSpace': 'technologytab',
    'TechnologyExpertise_Tab_BSpace': 'technologytab',
    'TechnologyExpertise_Tab_NoSpace': 'technologytab',
    'TWithTCML_3Box_Slider': 'related-services',
    'TWithTCML_3Box_Slider_WhiteBg': 'related-services',
    'CTA_TealBG': 'cta-teal',
    'TCM_ImageRight_TitleBG': 'title-bg-content-list',
    'TWithTCL_LightTealBG_4Section': 'title-four-col',
    'TC_GreyBG_TextLeft': 'title-four-list',
    'TCM_ImageRight_32': 'leftImage32',
    'TCMWithTCL_LeftImage_Nobg': 'nobg-leftimage-tcml',
    'Software_Product': 'floatimage-title-content-list',
    'TCWithTCL_4_NoBox': 'title-content-4col',
    'TWithTCML_BGimage_3icons_Top': 'title-fourCol-bg',
    'TCWithTCML_4icons_Left': 'elite-custom',
    'TCWithTCML_3Content': 'check-three-col',
    'Contact_Testimonial': 'client-testimonial',
    'TC_Two_Col_Center': 'title-two-list',
    'TCWithTCML': 'check-two-col-border',
    'TCWithTCML_NoBorder': 'checknoborder',
    'TC_JobOpenings_blackcol': 'op-threeblack-col',
    'TCMWithTCL_imageleft': 'fifty-fifty-image-left',
    'TCMWithTCL_imageleft_BgTeal': 'fifty-fifty-image-left',
    'TCL_threecol_bgwhite': 'title-threecol-bgwhite',
    'TWithTCML_4Box_IconTop': 'trendingtech',
    'TCWithTCML_3Box_IconTop': "threebox",
    'TCWithTCL_WhyUs': "whyus",
    'Maintenance_Methodology': 'tcwtcl-methodology',
    'TCM_ImageRight_DarkBG': 'tcm-imagright-darkbg',
    'ImageLeft_GreyBG': 'tcm-leftimg-1-3',
    'TCWithTCML_5icon_Top': 'tcmwtcml-5icon-top',
    'LightTealBG_ListCenter': 'tcl-bg-topcenterIcon',
    'TCWithTCL_GreyBG_6Points': 'application-ybb',
    'BGimage_ImageRight_4Points': 'bgimg-rightimgmove-4points',
    'BGimage_ImageLeft_4Points': 'bgimg-leftimgmove-4points',
    'ImageCenter_LightTealBG': 'tcmcl-moveImg',
    'Dark_BGimage_6sec': 'tc-sixcol',
    'TCWithTML_3image_Top': 'tcwithtml-3img-top',
    'TCWithTML_4image_Top': 'tcwithtml-3img-top',
    'LeftImage_DarkBG': 'tc-6-4-stickimage-left',
    'Communication_Channels': 'tc-1-2-hovericonright',
    'Mobilize_Banner': 'mobilize',
    'TCM_DarkBG_4Image_Below': 'tethersection',
    'TCWithTCML_Check_Icon': 'check-two-col-border',
    'TCWithTCML_Leftlist': 'title-inlineiconcontent',
    'TCM_ImageRight21_WhiteBG': 'content-right-img',
    'TCM_ImageRight1_2_WhiteBG': 'content-rightimg-col',
    'Development_Process_9icons_3col': 'development-process',
    'Development_Process_9icons_3col_nospace_bottom': 'development-process',
    'SoftwareDevelopment_Tab': 'verticaltabs',
    'TC_DarkBG': 'titlecont-cta',
    'DarkBG_6Section_IconTop': 'tc-sixcol',
    'TCM_ImageRight_WhiteBG': 'TCM_image-right',
    'TCM_TealBG_RightImage': 'TCM_image-right',
    'TCM_Insights': 'tckey-fourcol-value',
    'TCM_Insights_White': 'tckey-fourcol-value',
    'CTA_TealBG_CenterText': 'cta-teal-center',
    'LightBG_6Section_IconTop': 'tc-sixcol',
    'TCM_ImageBgRight': 'tcm-imagebg-right',
    'TCM_IconRight_Dark': 'bgimg-rightimg-list-dark',
    'TCM_IconLeft_LightTeal': 'bgimg-leftimg-list',
    'TCM_IconRight_Light': 'bgimg-rightimg-list-dark',
    'TCL_LeftRight': 'tc-1-2-list-half-bg',
    'Blog_Listing': 'blog-list',
    'TCWithTCML_Fourblog': 'title-fourimageblog',
    'SmallBanner': 'blog-banner',
    'CTA_Success_Last': 'CTA-success-last',
    'SS_FirstSection': 'heading-success',
    'TWithTML_IconTitle_4Box': 'icon-title-tieldback-col5', // real-estate
    'TWithTML_IconTitle_5TealBox': 'icon-title-tieldback-col5',
    'News_Listing': 'news-list',
    'CS_FirstSection': 'TCM_image-left-list-fifity',
    'CS_Hightlights': 'highlights-case-stuides',
    'CS_AboutProject': 'cs-about-project',
    'CS_Approach': 'cs-about-project',
    'CS_Proposed': 'cs-proposed',
    'CS_Achievement': 'cs-achievement',
    'CS_OverallProject': 'titlecont-cta',
    'TC_StaticContent': 'terms-policy',
    'TCWithTCL_TwoSection': 'acclaimedSoftware',
    'TC_RightText_HightLight': 'agile-section',
    'TM_Awards': 'logo-slider',
    'TM_Awards_NoTitle': 'logo-slider',
    'TM_Awards_YTitle': 'logo-slider',
    'TCWithTCML_Testimonial': 'content-list-slider',
    'TCWithTCML_SuccessStories': 'project-success',
    'TCM_ClientList': 'client-slider',
    'TWithTCML_SolutionVerticals': 'solutions-varied-verticals',
    'HomeBanner': 'home-banner',
    'HomeBanner_new_office': 'home-banner', // new-office
    'TCWithTCML_Dark_6point_2Col': 'bg-5050iconhover',
    'TWithTCL_4GrayBox': 'card',
    'TCM_DarkBG_2ColList75': 'bg-title-two-list',
    'TC5050WCList' : '5050-title-content-and-list',
    'TWithTCL_GreyBG_6Sec': 'grey-bg-6col',
    'TCWithTCML_Dark_6icons_Left': 'bg-5050iconhover',
    'TWithTeal_LeftalignBG_3Section': 'lightteal-left-align',
    'TCWithTCML_4icon_Teal_Top_With_Border': 'fouricon-top', // real-estate
    'SMS_4Row_Sec_TL': 'on-demand-services',
    'TCWithTCML_Contentlist-Media-ListBG-Gray': 'title-content-multimedia-contentlist', // bsp-os
    'TCWithTCML_CustomBG_6Box': 'title-content-3col',
    'FourIcon_BgSecondary': 'bg-secondary-threeicon',
    'TCM_ImageRight_ImgVisibleTLeft': 'TCM_image-right-visible', // bsp-os
    'TCMWithTCL_ImageCenter_TealBg_Partner': 'tcmc',
    'TCL_fourcol_Whitebg': 'tcl-fourcol',
    'TCWithTCL_Teal_4Box_HY':'card',
    'TWithTCL_LeftalignBG_4Section': 'left-title-four-col',
    'TCWithTCML_4icon_Top': 'fouricon-top',
    'TCWithTCML_4icon_Teal_Top': 'fouricon-top',
    'TWithLightTeal_LeftalignBG_4Section': 'lightteal-left-align',
    'TWithTCL_Next': 'what-next-3col',
    'TC_Teal_Two_Col_Center': 'tealbg-title-two-list',
    'TC_Teal_Two_Col_Center_Circle_List': 'tealbg-title-two-list',
    'TWithTCL_GreyBG_4Sec': 'grey-bg-4col',
    'TWithTCL_GreyBG_4Sec_dup': 'grey-bg-4col',
    'TCWithTCL_4Point_Process': '4col-arrow',
    'TWithTCL_LightTealBG_3Section': 'title-three-col',
    'TWithTCML_Process_BigIcon': 'circle-icon-content',
    'TWithTCML_4Box_IconTop_Center': 'card-3col-icon',
    'SMS_3Row_Sec': 'on-demand-services',
    'SMS_4Row_Sec': 'on-demand-services',
    'SMS_GreyBG_LeftImage_5050List': 'left-img-5050list',
    'SMS_TealBG_RightImage_5050List': 'leftimage-5050list-bglightblue',
    'SMS_RightImg_3Col': 'title-con-3iconcol',
    'TCWithTCML_Content-Media-List': 'title-content-multimedia-content',
    'TCWithTCML_Leftlist0': 'title-titlecontentlist-bgteild',
    'TCWithTCML_3icon_Top_Hover': 'title-threecol-topicon',
    'TCWithTCL_Title_List_CTA': 'title-content-list-botborder',
    'TCWithTCML_3icon_Top_Hover_Border': 'title-hoverborder-topicon',
    'LeadershipTeam_ImgRight': 'leader-ship',
    'LeadershipTeam_ImgLeft': 'leader-ship',
    'TCM_GreyBG_LeftImage': 'global-outsourcing',
    'TCM_RightImage_WhiteBg': 'left-content-right-img',
    'TCM_LeftImage_LightTealBG': 'right-content-left-img',
    'TCM_RightImage_DarkBG': 'left-content-right-img',
    'TCM_LeftImage_WhiteBG': 'right-content-left-img',
    'TCM_RightImage_GreyBG': 'left-content-right-img',
    'TCM_RightImage_LightTealBG': 'left-content-right-img',
    'Testimonial_3Col_Dark': 'customer-rating',
    'Testimonial_3Col': 'customer-rating',
    'CAD_Center_Img': 'floatingicon-circle',
    'HeaderInverse': 'header-inverse',
    'Header': 'header',
    'Footer': 'footer',
    'FooterLanding': 'footer-landing',
    'HeaderLanding': 'header-landing',
    'TCWithTCML_Leftlist_withoutcheck': 'title-titlecontentlist-bgteild',
    'Bgblue-Title-Content': 'head-para-bgblue',
    'Bgimage-List-CTA': 'title-list-cta-backimage',
    'TCWithBlogFeatured': 'success-stories-blogs',
    'TCWithBlogFeatured1-2': 'blog',
    'TCWithBlogFeatured1-3': 'blog',
    'TCWithBlogFeatured1-4': 'blog',
    'Bgblue-Title-twolist': 'bgblueimage-title-list',
    'Threelist-Bgoverlaygreen': 'title-3list-bgoverlaygreen',
    'Threeicon-Progressbar': '3iconround-progressbar',
    'TCWithTCML_Contentlist-Media-List': 'title-content-multimedia-contentlist',
    'TCMWithTCL_ImageCenter_DarkBg': 'tcmc',
    'TCMWithTCL_ImageCenter_GreyBg': 'tcmc',
    'AM_RotateImg_5Col': 'title-img-5col',
    'AM_2Col_ImgColl': '2colbg_imgxoll',
    'TCWithTCML_Leftlist_Darkbg': 'title-inlineiconcontent',
    'TCWithTCML_Checkicon_Leftlist': 'title-inlineiconcontent',
    'TCM_LeftconRightImage': 'leftlist-rightimg',
    'TWithTML_IconTitle_4TealBox': 'icon-title-tealbg-col4',
    'AM_LeftCon_RightList': 'title-con-right-list',
    'TCM_ImageRight_Square_list': 'TCM_image-right-visible',
    'TC_LightTealBG_12': 'lightteal-squarelist',
    'TCM_AfterImg': 'left-content',
    'TC_TealBG_TextLeft': 'title-four-list',
    'Fifty-Fifty-Que-Contentlist-Bg': 'fiftycontent-fiftylist-bgimage',
    'TCMWithTCML_RightImage_LeftIconList': 'icon-content-rightimage',
    'TCWithTCL_CustomBG_6Box': 'title-content-3col',
    'TCM_ImageLeft_ImgVisible': 'tcm-image-left',
    'TCM_ImageLeft_WhiteBG': 'tcm-image-left',
    'TCM_ImageLeft_Square_list': 'tcm-image-left',
    'AI_LeftCon_RightList': 'titlecontent-rightlist',
    'TCWithTCML_3icon_Card': 'card-iconcontent',
    'TCWithTCL_TealBG_8Box': 'tealbg-t-four-col',
    'TCWithTCML_4iconsBgGrey_Left': 'elite-custom',
    'TCWithTCML_NoHoverBgGrey_Left': 'elite-custom-hover',
    'TCWithTCML_NoHover_Left': 'elite-custom-hover',
    'TCWithTCML_4iconsBgGrey_NoHover': 'elite-custom-hover',
    'LightTeal_ImgNoHover': 'elite-custom-hover',
    'Secondary_ImgNoHover': 'elite-custom-hover',
    'TC_Teal_Two_Col_Center100': 'tealbg-title-two-list',
    'TC_GreyBG_12': 'lightteal-squarelist',
    'CMS_BgImgHover_6Col': 'cms-bgImghover-6col',
    'TCM_DarkBG_2ColList100': 'bg-title-two-list100',
    'TCM_GreyBG_2ColList100': 'bg-title-two-list100',
    'CMS_GreyBg_Center_FourCol': 'greybg-center-fourcol',
    'CMS_Title_Img4Col': 'title-img4col',
    'CMS_WhiteBgimage-Right': 'cms_bgimage-right',
    'CMS_GreyBgimage-Right': 'cms-bgimage-right',
    'Ecom_ImgHover4Col': 'ecom-imghover-4col',
    'Ecom_ImgHover2Col': 'ecom-imghover-4col',
    'TCM_BgImageLeft5050': 'fifty-fifty-img-left',
    'LightTeal_ImgHover_Sq_List': 'elite-custom',
    'TCWithTCML_3icon_Top_BgTeal': 'threeicon-top',
    'BgCustom_3icon_Card': 'bgcustom-card',
    'Count-Border-Content': 'countprocess',
    'Titleborder-8col-Greenbg-Contentleft': 'title-bottomborder-8blog',
    'TWithTCML_6Box_IconTop': 'threecol-icon-content-list',
    'Clients': 'client-logo-slider',
    'Text_Left_NoHover': 'textleft-nohover',
    'TCM_ImageRightLightTeal': 'fifty-fity-image-right',
    'TCM_ImageRightDark': 'fifty-fity-image-right',
    'TCMWithTCL_ImageCenter_MoveImg': 'tcmc-move-img',
    'TCMWithTCL_ImageCenter_MoveImg_Themelight10': 'tcmc-move-img',
    'SD_RightCon_LeftImg': 'fifty-leftimg-rightcon',
    'TCMWithTCL_ImageCenter_MoveImg_NoTitle': 'tcmc-move-img',
    'SixIconTop-Bgblue': 'icontop-bgblue',
    'Icon_Contentlist_4col': 'title-content-iconlist',
    'Title_Blog_IconList': 'two-col-content-iconlist',
    'Six-List-Centerimage': 'six-list-imagecenter',
    'AD_BgScrollRight': 'bgscrollright',
    'CTA_Center': 'cta-center',
    'SMS_GreyBG_RightImage_5050List': 'left-img-5050list',
    'TCMWithTCL_ImageCenter_DarkBgnoTitle': 'tcmc-notitle',
    'QA_FiftyFiftyImgList': 't-5050ImgList',
    'Industries_Details': 'threecol-details',
    'HM_Title_BeforeImage': 'right-title-img',
    'ThreeCol_BgImg': 'three-col-img',
    'TCM_LeftRight_CenterImg': 'lr-list',
    'TCM_ImageLeft_GreyBG': 'tcm-image-left',
    'ThreeIcon_BgSecondary': 'bg-secondary-threeicon',
    'TwoImg_TC': 'two-imgtitle',
    'AD_BgScrollLeft': 'bg-scrollleft',
    'AD_BgScrollRight_2Bg': 'bgscrollright2bg',
    'Three_Icon_Top_Hover': 'threeicnhover',
    'Title_Single': 'titleOnly-left',
    'FAQ_List': 'accordion',
    'TC_Two_Col_Center_SquareList': 'title-two-list',
    'Check-ThreeCol-BgImage': 'check-threecol-title-content-list',
    'Multi_Image': 'multi-image-content',
    'Fifty_Fifty_IconList_Cta': 'solution-fiftyfifty',
    'UI_CruveTab': 'our-approch-tab',
    'UI_5colImgCon': 'key-5colimg-con',
    'UI_TitleCon_3Col': 'title-con-img-3col',
    'TCL_threecol_bgwhite_Left': 'title-threecol-bgwhite',
    'UI_Title_6col': 'title-6col',
    'TCWithTCMLBGImage': 'bg-two-col-border',
    'TCM_ImageRight_ImgVisible': 'TCM_image-right-visible',
    'TCM_ImageRight_WhiteBgImgVisible': 'TCM_image-right-visible',
    'Tabbing_Slider': 'tabslider',
    'TC_WhiteBG_TextLeft': 'left-textonly',
    'TC_DarkBG_TextLeft': 'left-textonly',
    'Top_Fiveicon_BGwhite': 'greybg-center-fourcol',
    'TCWithTCL_Title_Sixcol_Bgimage': 'title-threecol-bgimg',
    'TCMWithTCL_ImageCenter_TealBg': 'tcmc',
    'TL_FourCol-TealBG': 'tl-forcol',
    'TCL_fourcol_Greybg': 'tcl-fourcol',
    'TCL_fourcol_Whitebg_space': 'tcl-fourcol',
    'SMS_GreyBG_RightImage_fiftyColList': 'left-img-5050list',
    'TCMWithTCL_BGTeal_8Box': 'bgimage-eightbox',
    'TM_AutoCol_JustCenter': 'tm-autocol-justcenter',
    'TCWithTCL_Dark_1by2': 'tcl-dark-checklist-12',
    'TCWithTCML_Grey': 'check-two-col-border',
    'TWithTCML_TabWithContent': 'twithtcml-contenttab',
    'TWithTML_IconTitle_4TealBox_Full': 'icon-title-tealbg-col4',
    'Inner_Menu': 'inner-submenu',
    'TC_Teal_Two_Col_Center_ContentBlack': 'tealbg-title-two-list',
    'AM_LeftCon_RightList_TealBG': 'title-con-right-list',
    'TCM_WhiteBG_RightImage': 'left-content-list-right-img',
    'TCM_GreyBG_RightImage': 'left-content-list-right-img',
    'TC_Center_WhiteBG100_Left': 'common-heading',
    'TWithTCML_1_4_List': 'twtcml-1-4-list',
    'TWithTCML_1_4_List_Bspace': 'twtcml-1-4-list',
    'TML_Imageback_SquareList': 'solution-rightlist-backimage',
    'TL_ThreeCol-TealBG': 'tl-Threecol',
    'TCMWithTCL_RCTBox': 'tcmwtcl-rctbox',
    'TCM_7_3_Col': 'tcm-7-3-col',
    'SMS_GreyBG_RightImage_White': 'left-img-5050list',
    'TL_ThreeCol_TealBG_full': 'tl-Threecol',
    'TL_ThreeCol_WhiteBG_full_CheckList': 'tl-Threecol',
    'TCM_List_Full': 'tcm-list-full',
    'QA_FullImgList': 't-5050ImgList',
    'TCWithTCML_Teal_6point_2Col': 'bg-5050iconhover',
    'TC_WhiteBG_7': 'lightteal-squarelist',
    'TCL_fourcol_whitebg': 'tcl-fourcol',
    'TCWithTCML_5icon_Teal_Top': 'fiveicon-top',
    'TCWithTCML_3icon_Top_GrayBg': 'threeicon-top',
    'TC_DarkBG_TextCenter': 'title-four-list',
    'TC_LightTealBG_TextLeft': 'title-four-list',
    'Fifty_Fifty_IconList_Cta_Imageright': 'solution-fiftyfiftyright',
    'Fifty_Fifty_IconList_Cta_Imageleft': 'solution-fiftyfiftyleft',
    'TCMWithTCL_Teal_6Sec': 'roundicon-3col-bgwhite',
    'TCWithTCML_6Box_IconTop_Dark': 'tcwtcml-6-topicon',
    'TCWithTCML_Rainbow_6Box': 'tcwtcml-6box',
    'TCM_2ColList75': 'bg-title-two-list',
    'Industries_Details_Yspace': 'threecol-details',
    'FourIconTopLeft': 'fouriconleft',
    'TCWithTCML_InnerBox_Grey': 'twocolborderinner',
    'TCWithTCML_3icon_Top_Hover_Bg': 'threeicontopbg',
    'Title_Center_TealBg_List': 'titlecentertealbg',
    'HM_Title_BeforeImage_Small': 'right-title-imgsmall',
    'AlternateImgContent': 'four-col-img',
    'Img_Title_3Card': 'imgtitlethreecard',
    'BgCustom_4icon_Card': 'bgcustom-card',
    'LeftImg_Accordion': 'leftimgacc',
    'HR_CenterImg2ColGrey': 'center-img-2col',
    'HR_CircleCenterImg': 'circle-centerimg',
    'TCWithTCML_3icon_Top_HoverBGGrey': 'title-threecol-topicon',
    'HR_5050RightList': 'hr-5050rightlist',
    'TCWithTCML_Check_Icon_noBottom': 'check-two-col-border',
    'ISS_BG3ColList': 'bg3collist',
    'Premium_Innovation': 'premium_innovation',
    'TCWithTCML_3icon_Top_HoverBGTeal': 'title-threecol-topicon',
    'LeftRight_BGImgCON': 'left-rightbgimgcon',
    'TCM_BgImgLeft5050CircleList': 'fifty-fifty-img-left',
    'BD_ImgRightLeftButton': 'img-rightleft-conbtn',
    'TCM_ImageLeft_GreyBGImgVisible': 'tcm-image-left',
    'TCL_fourcol': 'tcl-fourcol',
    'Software_Product_Upgrade': 'software-upgrade',
    'TCM_BgImageRightDark': 'fifty-fity-image-right',
    'TWithTCL_WhiteBG_4Sec': 'grey-bg-4col',
    'TC_WhiteBG_12': 'lightteal-squarelist',
    'FW_5050listLRBorder': '5050list-lrborder',
    'TCM_ImageRightTeal': 'fifty-fity-image-right',
    'BgCustom_3icon_CardNoHover': 'bgcustom-card',
    'TCWithTCML_3icon_TealCard': 'card-iconcontent',
    'GA_ImgColBGGrey': 'imgcol-bggrey',
    'Count-Border-Content4col': 'countprocess',
    'Count-Border-Content3col': 'countprocess',
    'TCWithTCL_Teal_4BoxLeft': 'card', 
    'CD_6ColImgcol': 'cd-6colimgcol',
    'CD_TCM_Img': 'cd-tmimgblock',
    'FD_LeftImgMovRightCon': 'left-imgmov-rightcon',
    'FD_BgimgLeftCon': 'bgimg-leftcon',
    'RN_4ColImgCenter': '4colimg-centerspace',
    'TCM_MultiImage': 'fsm-multiimage-content',
    'TCMWithTML_12_IconList': 'solution-50imagecontent',
    'TCMWithTML_12_Black': 'solution-50imageupgrade',
    'TH_ZigZag_Content': 'tah-content-imagesquare',
    'TWithTCML_Process_BigIcon_teal': 'circle-icon-content',
    'AM_LeftCon_RightList_GreyBg': 'title-con-right-list',
    'TCM_ImageLeft_WhiteBG_ImgVisible': 'tcm-image-left',
    'TCM_ImageRight_1_7': 'TCM_image-right-visible',
    'TC_WhiteBGPara_sm': 'lightteal-squarelist',
    'TC_DarkBGTitle_TextLeft': 'title-four-list',
    'AM_LeftCon_RightList_GreyBG': 'title-con-right-list',
    'AD_LeftImgRightList': 'ad-leftimgrightlist',
    'TCM_RightList_Square_list': 'titlecontent-rightlist',
    'TWithTCL_4BGImgBox': 'card',
    'TWithTCL_TealBG_4Sec': 'grey-bg-4col',
    'TC_BgTealTwo_Col_Center': 'title-two-list',
    'TCM_GreyBgImageRight': '8-4imageright',
    'TCM_ImageBgLeftTeal': 'tcm-imageleft-translate',
    'TCL_threecol_bggray_Left': 'title-threecol-bgwhite',
    'CS_Listing': 'case-studies-list',
    'Blog_Featured': 'blog-featured',
    'SS_Listing': 'success-stories-blogs',
    'SS_Testimonial': 'leftround-image-content',
    'SS_Hightlight': 'heading-border-teild-content',
    'SS_TealBG_Text': 'quoteicon-bgteild-content',
    'SS_RightImage': 'teildtitle-content-image',
    'SS_Ratings': 'rightimage-quoteicon',
    'SS_RightText_Title': 'border-heading-multicontent',
    'SS_GreyBG_Text': 'quoteicon-bggray-content',
    'SS_RightText_NoTitle': 'que-ans',
    'SS_FinalThoughts': 'border-heading-content',
    'SS_DarkBG_Text': 'bgblue-content',
    'TCWithTCL_MoreTopics': 'exploretopics',
    'TCM_Subscribe': 'footeremail',
    'Blog_Category': 'blog-categories',
    'Blog_details': 'blog-detail',
    'Case_Studies_Categories': 'case-studies-categories',
    'Case_Studies_Details': 'case-studies-detail',
    'ContentList_Design': 'contentlist',
    'ThreeIconLeft': 'threeicontopLeftalign',
    'CardIconLeft': 'cardlefticon',
    'Title_Only': 'titleonly',
    'Client_Testimonial': 'client-testimonials',
    'Testimonial_Slider': 'client-testimonial-slider',
    'TC_LightTealBG_CircleList': 'lightteal-squarelist',
    'Team_Glory': 'glory-team',
    'TCML_Cultures': 'tcml-cultures',
    'TCWithTCML_5050-Media-List': 'title-content-multimedia-content',
    'TC_Center_TealBG': 'tc-center-tealbg',
    'TCM_GreyBG_Left_Image': 'right-content-list-left-img',
    'TCM_LightTealBG_Left_Image': 'right-content-list-left-img',
    'TCM_WhiteBG_Left_Image': 'right-content-list-left-img',
    'Video_Listing': 'video-list',
    'Video_Categories': 'video-categories',
    'TC_FeaturedJobs': 'featuredJobs',
    'GAD_AllJobs': 'joblisting',
    'FeaturedVideo': 'featuredvideo',
    'FeaturedVideos2col': 'featuredvideo',
    'BGDark_ThreeImgTop': 'darkImgthreecol',
    'BgIMG_4Card': 'cardbg',
    'TealListTwoCol': 'listtwocol',
    'ImageGallery': 'imagegallery',
    'OpenPosition3Col': 'threecolList',
    'TitleListLeftAlgin': 'titlelistleft',
    'Classifications': 'classifications',
    "Whitepaper_Listing": 'whitepaper-list',
    "Guide_Listing": 'guide-list',
    'AU_ImgTop_5Col': 'au-imgtop-5col',
    'AU_TealBg_3Box': 'au-tealbg-3box',
    'RN_5ColImgCenter': '4colimg-centerspace',
    'AU_3ColImg': 'au3colimgleader',
    'SCS_Form_Banner': 'scs-form-banner',
    'TCML_Form': 'tcml-form-content',
    'Author_Banner': 'author-banner',
    'TCML_GrenBg_Fifty': 'tcml-fifity-pdf',
    'TCWithBlogFeatured1-3Bspace': 'blog',
    'TCWithBlogFeatured1-3Nospace': 'blog',
    'TM_Awards_Yspace': 'logo-slider',
    'HireLanding_PHPBanner': 'hirelandingphpbanner',
    'HL_PHPImgRightLeftCon': 'hlphpcallingsuper',
    'HL_PHPLeftConArrow': 'hlphpleftarrow',
    'HL_PHP2ImgCon': 'hlphp2imgcon',
    'HL_PHP_TCBGImg': 'hlphptitleconbgimg',
    'HL_PHPCTA_Center': 'hl-phpcta-center',
    'HY_4ColImgTitleCenter': '4colimgTitle-centerspace',
    'TCWithTCML_NOCheck_Icon_BG_Gray': 'check-two-col-border',
    'HirePHPVideoBlock': 'hirephpvideoblock',
    'ContentList_Design_NoBorder': 'contentlist',
    'TCMC_6Col': 'tcmc-6col',
    'TCMC_6ColTealBg': 'tcmc-6col',
    'HireLanding_SoftDevBanner': 'hiresoftdevbanner',
    'HireSoftDevCenterWhite': 'hiresoftdevcenterbg',
    'HireSoftdevIconCenterTop': 'hiresoftdevicontop',
    'HireSoftDevRightTitleLeftList': 'hsdrighttitleleftlist',
    'HireSoftDevSlider': 'hiresoftdevslider',
    'HireSoftDevTabbing': 'hiresoftdevtabbing',
    'HireSoftDevTCMSlider': 'hiresoftdevtcmslider',
    'HireSoftdevImgColList': 'hsdimghoverlist',
    'HireSoftDevTabbingIcon': 'hiresoftdevtabbingicon',
    'HireSoftDevContactUS': 'hiresoftdevcontactus',
    'PE_BGImgSlider': 'pe-bgimgslider',
    'PE_ContactForm': 'pe-contactform',
    'PE_Checklist_btn': 'pe-checklistbtn',
    'PE_LRImgNOBorderBGGrey': 'pe-lrimgnobordergrey',
    'PE_BorderBottomIcon': 'pe-borderbottomicon',
    'PE_Banner': 'pe-banner',
    'CSD_Banner': 'csd-banner',
    'CSD_4ColTeal': 'csd-4colteallist',
    'CSD_ThreeIconTop': 'csd-threeicontop',
    'Icon_Contentlist_4colWhiteBG': 'title-content-iconlist',
    'CSD_TabbingImg': 'csd-tabbingimg',
    'CSD_FullwidthLogoSlider': 'csd-fullwidthlogoslider',
    'CSD_FullwidthLogoSliderNoTitle': 'csd-fullwidthlogoslider',
    'TCM_TCC_Thankyou': 'wp-thankyoubanner',
    'WP_5050TitleList': 'wp-5050titlelist',
    'WP_JoinNowForm': 'wp-joinnowform',
    'TCML_Dark_List': 'service-leftimg-list',
    'TCMLR_Dark_List': 'service-rightimg-list',
    'TCMLR_Grey_List': 'service-rightimg-list',
    'TCML_Grey_List': 'service-leftimg-list',
    'TCML_Teal_List': 'service-leftimg-list',
    'TCMLR_White_List': 'service-rightimg-list',
    'TCM_content_bg': 'anvrsry-title-content',
    'TCM_con_left_bgimage': 'anvrsry-50content-bgimage',
    'TM_5Col_JustCenter': 'tm-5col-justcenter',
    'Openings': 'opening-page',
    'TCML_GreyBg_Fifty': 'tcml-fifity-pdf',
    'Opening_Sidebar': 'current-opening-sidebar',
    'Career_details': 'career-details',
    'TCM_RW_Thankyou': 'wp-thankyoubanner',
    'HireRemoteDevVideoBlock': 'hireremotevideoblock',
    'CS_Testimonial': 'cs-testimonial',
    'CS_Proposed_3Col': 'cs-proposed-3col',
    'CS_Proposed_LoopedContent': 'cs-proposed-loopedcontent',
    'CS_Result': 'cs-about-project',
    'TC_CS': 'tc-cs',
    'TC_CS_Dark': 'tc-cs',
    'TCL_CSGray': 'tcl-csgray',
    'CS_Proposed_LoopedContent_LightTeal': 'cs-proposed-loopedcontent',
    'TC_CS_Dark_Left': 'tc-cs',
    'CS_Proposed_LoopedContent_Dark': 'cs-proposed-loopedcontent',
    'CS_Proposed_LoopedContentBgImg': 'cs-proposed-loopedcontent',
    'CS_FirstSection100': 'TCM_image-left-list-fifity',
    'TC_CS_LightTeal': 'tc-cs',
    'CS_Proposed_3ColDark': 'cs-proposed-3col',
    'SS_Listing_twocol': 'success-stories-twoblog',
    'TCM_title_content_btn_center': 'anvrsry-title-content-cta',
    'TCM_title_content_btn_center_darkbg': 'anvrsry-title-content-cta-darkbg',
    'TCM_freedback_boss': 'anvrsry_leading_slider',
    'TCM_topicon_slider': 'anvrsry-topicon-slider',
    'TCM_rx_gallery': 'anvrsry-rx-gallery',
    'TCM_year_celebration': 'anvrsry-21year-complete',
    'TCM_main_banner_anyvrsry': 'anvrsry-main-banner',
    'TCM_video': 'anvrsry_video',
    'anvrsry_footer': 'anvrsry-footer-design',
    'new_office_footer': 'office-footer-design', // new-office
    'Landing-Footer': 'landing-footer',
    'CS_AboutProjectYSpace': 'cs-about-project',
    'CS_Proposed_3ColGrey': 'cs-proposed-3col',
    'HireRemoteDevHeader': 'hireremotedev-header',
    'ES_IconNoHover': 'es-iconnohover',
    'ES_Header': 'es-header',
    'PEHeader': 'pe-header',
    'PE_LRImgNOBorderBGWhite': 'pe-lrimgnobordergrey',
    'TCM_Icon_Content_Medialist': 'icon_tcm_list',
    'TCM_Icon_Content_Left': 'icon-contentlist-left',
    'TCM_VideoList': 'videolist',
    'TCMWithTCL_Dark_6Sec': 'roundlist-content',
    'CSD_Accordian': 'csd-accordian',
    'Success_Stories_1_2': 'successtories-1-2',
    'SS_Heading': 'ss_heading',
    'TCM_ImageRightLightTealCircleList': 'fifty-fity-image-right-circlelist',
    'HeaderContactUs': 'header-contact-us',
    'TCM_ImageRight_7_5BGTeal': 'tcm-imgright-7-5',
    'TCM_ImageRight_ImgVisibleDarkMode': 'TCM_image-right-darkmode',
    'TCM_ImageLeft_ImgVisibleDarkMode': 'TCM_image-left-darkmode',
    'Header_mobile': 'header-mobile',
    'Contact_Common_Head': 'contactus-common-heading',
    'Home_Blog_List': 'home_blog',
    'TC_Two_Col_CenterTSpace': 'title-two-list-tspace',
    'CTA_BlackBG': 'cta-blue',
    'TWithTCML_3Box_Slider_WhiteTspace': 'related-services',
    'Multimedia_Graybg': 'title-content-multimedia-content',
    'AM_2Col_ImgColl6': '2colbg_imgxoll',
    'TC_BGGrey_TextLeft': 'left-textonly',
    'TCMWithTCL_7_5_LeftImage': 'leftimage-tcml',
    'TCMWithTCL_ImageCenter_react':'tcmc',
    'TWithTCML_TabWithContent_Bdc':'twithtcml-contenttab',
    'TCMWithTCL_BGTeal_8Box_Net':'bgimage-eightbox',
    'TCMWithTCL_ImageCenter_Net':'tcmc_centerimage',
    'TCWithTCML_Check_Icon_Cs':'check-two-col-border',
    'TCWithTCL_Teal_4Box_Cp':'card',
    'Card_Nospace':'cardNotop',
    'Card_Yspace':'cardNotop',
    'Card_Bspace':'cardNotop',
    'CTA_TealBG_php':'cta-teal',
    'TL_FourCol-TealBG_Core':'tl-forcol',
    'TCM_ImageLeft_WhiteBG_ImgVisible_Fw':'tcm-image-left',
    'TM_AutoCol_JustCenter_Aws':'tm-autocol-justcenter',
    'TWithTML_IconTitle_4TealBox_zoho':'icon-title-tealbg-col4',
    'TCWithTCML_Check_Icon_Lds':'check-two-col-border',
    'TWithTCML_TabWithContent_Mean':'twithtcml-contenttab',
    'TCL_fourcol_Greybg_Wp':'tcl-fourcol',
    'TCWithTCML_4icons_Left_Jd':'elite-custom',
    'TC_WhiteBG_Sd':'lightteal-squarelist',
    'TCWithTCL_TealBG_6Box_Sd':'title-content-3col',
    'FW_5050listLRBorder_Dm':'5050list-lrborder',
    'TC_Two_Col_Center_SquareList_Sd':'title-two-list',
    'TCWithTCML_Teal_6point_2Col_Swd':'bg-5050iconhover',
    'TCWithTCML_Dark_6point_2Col_Rd':'bg-5050iconhover',
    'TWithTCL_WhiteBG_6Sec_Wd':'roundicon-3col-bgwhite',
    'TCL_threecol_bgwhite_Left_Xd':'title-threecol-bgwhite',
    'TCWithTCML_Check_Icon_Xd':'check-two-col-border',
    'TCMWithTCL_ImageCenter_Rd':'tcmc',
    'TCM_GreyBG_LeftImage_Description':'contentInlineList',
    'FD_LeftImgMovRightCon_hover':'left-imgmov-cta',
    'Count-Border-Content5col':'countprocess',
    'TCWithTCML_Check_Icon_Single_Icon':'check-two-col-single-icon',
    'TCMWithTCL_ImageCenter_html':'tcmc',
    'TCWithTCML_Check_Icon_Azure':'check-two-col-border',
    'TL_FourCol-TealBG_Html':'tl-forcol',
    'TL_FourCol-TealBG_Core_Tspace':'tl-forcol',
    'TWithTCL_WhiteBG_6Sec_Tspace':'roundicon-3col-bgwhite',
    'SMS_4Row_Sec_Bspace':'on-demand-services',
    'CTA_TealBG_Aws':'cta-teal',
    'Count-Border-Content4col_Tspace':'countprocess',
    'TCWithTCML_NoHover_Left_NoSpace':'elite-custom-hover',
    'Tabbing_Slider_Tbspace':'tabslider',
    'TCWithTCML_4iconsBgGrey_Left_Bggray':'elite-custom',
    'Development_Process_5icons': 'development-process', 
    'TCWithTCML_3Content_bgTeal': 'check-three-col',
    'TMWith_TM_List': 'fouricon-title-top',
    'TCM_ImageRight_Tlink': 'tlink-content-rightImg',
    'TCM_White_BG_LeftImage': 'global-outsourcing',
    'TCWithTML_3image_Top_bg': 'tcwithtml-3img-top-bg',
    'TCL_fourcol_Nobottom_Space': 'tcl-fourcol',
    'TWith_multiMedia_list': 'title-medialist',
    'TC_BgImage': "lightteal-squarelist",
    'TC_DarkBG_2ColTCList': 'tc-darkbg-2coltclist',
    'TCM_CTALink': 'titlecontent-media-ctalink',
    'TC_with_CTA_link': 'titlecontent-media-ctalink',
    'Title_Blog_IconList_Bgwhite': 'two-col-content-iconlist',
    'CTA_BgImageWhite_Center' : 'cta-bg',
    'Bgblue-Title-twolist-cta': 'bgblueimage-title-list',
    'TCM_ImageLeft_WhiteBG_ImgVisible_bg':'tcm-image-left',
    'TCWithTCMListSlider':'tcWithTCMListSlider',
    'TWithTCMListSlider':'twithTCMListSlider',
    // 'Radix-permier-league' : 'radix-premier-league',
    'PAYMENT_FORM_PAYPAL': 'paypal-form',
    // 'BgImageMListPicnic': 'bgImageMListPicnic',
    // 'MListPicnic':'mediaListPicnic',
    // 'PicnicAddress':'picnicAddress',
    // 'HeaderOnlyLogo':'header-only-logo',
    'TCWithTCML_Grey_space':'check-two-col-border',
    'TCWithTCML_3Content_Check':'check-three-col',
    'TCMWithTCL_ImageCenter_Md':'tcmc',
    'TC_WhiteBG_Sd_Nospace':'lightteal-squarelist',
    'TCL_threecol_bgwhite_Left_Nospace':'title-threecol-bgwhite',
    'News_details':'news_description',
    'Demo':'demo',
    'TC_WhiteBG_TextLeft_NoTitle':'content-only',
    'React_Dev_menu':'React-dev-menu', //react-dev
    'React_Dev_TCM':'React-dev-TCM', // react-dev
    'React_Dev_TCMWithTCML':'React-dev-TCMWithTCML', // react-dev
    'React_Dev_TCMWithTCMLIcons':'React-dev-TCMWithTCMLIcons', // react-dev
    'React_Dev_TCMWithTCMLImageFirst':'React-dev-TCMWithTCMLImageFirst', // react-dev
    'React_Dev_CTA':'React-dev-CTA', // recat-dev
    'React_Dev_Main':'React-dev-Main', // recat-dev
    'CTA_GrayBg':'cta-gray',
    'TCWithTCL_4_NoBox_BgWhite': 'title-content-4col',
    'TCM_RightImage_GreyBG_Tbspace':'left-content-right-img',
    'Testimonial_3Col_LightTeal':'customer-rating',
    'TCM_ImageLeft_GreyBGImg': 'tcm-image-left',
    'CTA_BgImageWhite_Center_bg':'cta-bg',
    'TCM_ImageLeft_TealBG':'tcm-image-left',
    'TCM_rx_gallery_space':'anvrsry-rx-gallery',
    'TCM_DarkBG_1ColList100':'bg-title-one-list100',
    'TM_Awards_YTitle_noSpace':'logo-slider',
    'TCM_video_BGTeal': 'anvrsry_video',
    'TCWithTCM_CircleList': 'tcWithTCM_CircleList', 
    'TCWithCircleListFullWidth': 'tcWithCircleList', 
    'TCWith_4Col_CircleList': 'tcWithCircleList', 
    'NoTitleWith_4Col_CircleList': 'tcWithCircleList',
    'TCWithTCL_Rainbow_4box': 'tcwithTCL_Rainbow_4box',
    'TCMWithTCSimpleList':'tcmWithTCSimpleList',
    'TCMWithTCL_LeftImage_LTeld':'leftimage-tcml',
    'TCM_ImageRight_7_5BGwhite':'tcm-imgright-7-5',
    // 'SmallBanner_Author':'author',
    'TCM_GreatPlace_Video':'great-place-video',
    'TCM_ImageRight_7_5BGgrey':'tcm-imgright-7-5', //jinal
    'TCL_threecol_bgwhite_Left_Xd_space':'title-threecol-bgwhite',
    'PageNotFound':'page-not-found', //parth
    'SmallBanner_policy':'blog-banner', //jinal
    'TCM_ImageRight_7_5BGwhite_squareList':'tcm-imgright-7-5', //jinal
    'GPTW_HomePage': 'custom-section-homepage',
    'SMS_4Row_Sec_RE': 'on-demand-services',
    'TCL_fourcol_whitebg_sd': 'tcl-fourcol',
    'InsightsBanner': 'insightsbanner',
    'EliteCustomDarkBG': 'eliteCustomBg',
    'EliteCustomLightBG': 'eliteCustomBg',
    'InsightsListing': 'insights-listing',
    'Software_Product_Dt': 'floatimage-title-content-list-dt',//Ankita
    'TCMWithTCL_TeldbgImage_8Box': 'bgimage-eightbox-teldbg', //Ankita
    'InsightsBannerSlider':'insight-banner-slider',
    'TCL_threecol_bgwhite_Left_NoTSpace':'title-threecol-bgwhite',
    'TCWithTCL_TealBG_6Box_TCWTCDH3':'title-content-3col',//Ankita for SEO purpose
    'TC_CareerForm':'carrer-form',
    'TCWithTCML_3icon_Top_LightTealBg':'threeicon-top',
    'TC_Center_BGTeal_Left': 'common-heading',
    'TC_Two_Col_Center_SquareList_Sd_space':'title-two-list',  
}