module.exports = {
    'SCS_01': "banner",
    'TCM_01': "why-us",
    'TCM_H1_01': "why-us-h1",
    'KVL_01': "top-rated",
    'TCWithBAIL': "our-expertise",
    'TCWithTCML_Why_Us': "service-slider",
    'TCWithTML_01': "masonary",
    // "TCM_02": "our-clients",
    'TCWithTCML_Easy_Steps': "how-it-works",
    'CTA_Service_CTA': "getintouch",
    'TCMWithTCL_01': "testimonials",
    'TCWithBlogL_01': "blog",
    "TCWithTCML_Service_List_23": "range-of-cards-2-3",
    "TCWithTCML_Service_List_13": "range-of-cards-1-3",
    "TCWithTCML_Service_List_12": "range-of-cards-1-2",
    "TCWithPL_Portfolio": "portfolio-service-list",
    // "TCWithPL_Portfolio_Content": "portfolio-service-content",
    "TC_Service_Expertise": "service-common-heading",
    "TC_Service_Points": "services-list",
    "TC_Service_Points_12": "services-list-1-2",
    "TCM_Service_Desc": "highlighted-banner",
    "TCM_Service_Desc_Invert": "highlighted-banner-invert",
    "TCWithTCL_Price": "pricing",
    // "TCWithBAIL_12": "compare-slider-1-2",
    "FAQL_FAQ": "accordion",
    "TC_Title_Sub": "title-sub",
    "TCM_02": "our-clients",
    "Blog_details": "blog-detail",
    "Portfolio_Banner": "blog-banner",
    "SCS_Short": "short-banner",
    "Title_Content_Icon_Left": "tc-icon-left",
    "TCWithTCML_4_icon": "tc-icon-top",
    "TCWithTCML_Tab": "about-us-tabing",
    "Breadcrumb": "breadcrumbs-banner",
    "Breadcrumb_No_Banner": "breadcrumbs",
    // "TCWithBAIL_Service_Banner": "service-banner",
    "TCWithBAIL_Nxt_Prv": "our-expertise-nxt-prv",
    "Blog_Listing": "blog-list",
    "TC_H1": "common-content-h1",
    "Blog_Category": "blog-categories",
    "Blog_Tags": "blog-tags",
    "Blog_Featured": "blog-featured",
    "BackToPortfolio": "back-to-portfolio",
    "TCWithTCML": "contact-us-form",
    "SCS_BG_TextCenter": "landingBanner",
    "TCWithSlide_12": "compare-vue-slick-12",
    "TCM_Thankyou": "thank-you",
    "Landing_Desc": "landing-servicedesc",
    "TCM_LandingPage_Form": "landing-contact-us",
    "Landing_Page_Footwear_Contact": "landing-contact-us-footwear",
    "TCWithBAIL_Landing_Banner": "landing-page-banner",
    "Landing_Banner_Media": "landing-photo-editing-banner",
    "Landing_TCM": "landing-page-tcm",
    "Landing_Discount": "landing-discount",
    "Text_Left_Banner": "landing-footwear-banner",
    "Landing_Our_Client": "landing-our-client",
    "TCMWithTCML_Landing_ThankYou": "thank-you-landing-page",
    "TCWithTCML_Why_IIP_Footwear": "why-us-landing-page",
    "TC_Upload_Photo": "upload-form",
    "TC_Payment": "paypal",
    "Landing_Page_Jewelry_Contact": "landing-contactus-jewelry",
    "TCM_LPF_Photo_Retouching_India": "landing-retouching-form"
}